/*
 * glcd_types.h
 *
 *  Created on: 02.05.2020
 *      Author: matti
 */

#ifndef INC_UI_GLCD_TYPES_H_
#define INC_UI_GLCD_TYPES_H_

#if GLCD_PWM_TIMER_CH == 1
#define GLCD_PWM_CHANNEL_CFG \
   {PWM_OUTPUT_ACTIVE_LOW, NULL}, \
   {PWM_OUTPUT_DISABLED, NULL}, \
   {PWM_OUTPUT_DISABLED, NULL}, \
   {PWM_OUTPUT_DISABLED, NULL}
#elif GLCD_PWM_TIMER_CH == 2
#define GLCD_PWM_CHANNEL_CFG \
   {PWM_OUTPUT_DISABLED, NULL}, \
   {PWM_OUTPUT_ACTIVE_LOW, NULL}, \
   {PWM_OUTPUT_DISABLED, NULL}, \
   {PWM_OUTPUT_DISABLED, NULL}
#elif GLCD_PWM_TIMER_CH == 3
#define GLCD_PWM_CHANNEL_CFG \
   {PWM_OUTPUT_DISABLED, NULL}, \
   {PWM_OUTPUT_DISABLED, NULL}, \
   {PWM_OUTPUT_ACTIVE_LOW, NULL}, \
   {PWM_OUTPUT_DISABLED, NULL}
#elif GLCD_PWM_TIMER_CH == 4
#define GLCD_PWM_CHANNEL_CFG \
   {PWM_OUTPUT_DISABLED, NULL}, \
   {PWM_OUTPUT_DISABLED, NULL}, \
   {PWM_OUTPUT_DISABLED, NULL}, \
   {PWM_OUTPUT_ACTIVE_LOW, NULL}
#else
#error "Channel number not supported"
#endif

#define GLCD_PWM_US_TO_TICKS(x)  ((GLCD_PWM_TIMER_FREQ/1000000)*(x))
#define GLCD_PWM_PERIOD_TICKS    GLCD_PWM_US_TO_TICKS(GLCD_PWM_TIMER_P_US)

#define GLCD_SPI_CR1             (GLCD_SPI_CR1_MODE| GLCD_SPI_CR1_BR)
#define GLCD_SPI_CR2             0

#endif /* INC_UI_GLCD_TYPES_H_ */
