/*
 * drill_ctrl_types.h
 *
 *  Created on: 10.05.2020
 *      Author: matti
 */

#ifndef INC_APP_DRILL_CTRL_TYPES_H_
#define INC_APP_DRILL_CTRL_TYPES_H_

#define DRILL_CTRL_VERSION_START      V
#define DRILL_CTRL_VERSION_DEL        .
#define DRILL_CTRL_TI_STR_NX(A)       #A
#define DRILL_CTRL_TO_STR(A)          DRILL_CTRL_TI_STR_NX(A)
#define DRILL_CTRL_VERSION_EXP        DRILL_CTRL_TO_STR(DRILL_CTRL_VERSION_START) \
  DRILL_CTRL_TO_STR(DRILL_CTRL_MAJOR_VERSION) \
  DRILL_CTRL_TO_STR(DRILL_CTRL_VERSION_DEL) \
  DRILL_CTRL_TO_STR(DRILL_CTRL_MINOR_VERSION)

#define DRILL_CTRL_VERSION            DRILL_CTRL_VERSION_EXP


#endif /* INC_APP_DRILL_CTRL_TYPES_H_ */
