/*
 * drill_ctrl_cfg.h
 *
 *  Created on: 10.05.2020
 *      Author: matti
 */

#ifndef INC_APP_DRILL_CTRL_CFG_H_
#define INC_APP_DRILL_CTRL_CFG_H_

#define DRILL_CTRL_MAJOR_VERSION  0
#define DRILL_CTRL_MINOR_VERSION  1


#define DRILL_CTRL_MAIN_THREAD_STACK  512
#define DRILL_CTRL_MAIN_THREAD_PRIO   (NORMALPRIO - 1)
#define DRILL_CTRL_MAIN_THREAD_P_MS   25


#define DRILL_CTRL_MIN_SETPOINT       200
#define DRILL_CTRL_MAX_SETPOINT       2000
#define DRILL_CTRL_DEFAULT_SETPOINT   200
#define DRILL_CTRL_MIN_ESC_OUTPUT     500

#endif /* INC_APP_DRILL_CTRL_CFG_H_ */
